# Generated by Django 5.1.1 on 2024-10-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cassette', '0002_alter_playlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist',
            new_name='playlist_title',
        ),
    ]
