# Generated by Django 5.1.1 on 2024-10-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassette', '0003_rename_playlist_playlist_playlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
