# Generated by Django 5.1.1 on 2024-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_plyuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyuser',
            name='uuid',
            field=models.UUIDField(default='631a9b', editable=False, unique=True),
        ),
    ]
