# Generated by Django 5.1.1 on 2024-10-03 00:51

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_plyuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyuser',
            name='uuid',
            field=models.CharField(default=account.models.generate_short_uuid, editable=False, max_length=6, unique=True),
        ),
    ]
