# Generated by Django 5.1.1 on 2024-10-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_plyuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plyuser',
            name='name',
        ),
    ]
